- name: Docker install automation
  hosts: web1
  tasks:
    - name: Install Docker
      become: yes
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']
        state: present

    - name: Add Docker GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Update apt package cache
      become: yes
      apt:
        update_cache: yes

    - name: Install Docker packages
      become: yes
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present

    - name: Start Docker service
      become: yes
      service:
        name: docker
        state: started
        enabled: yes

