---
# tasks file for myrole
    - name: Install Docker
      become: yes
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']
        state: present

    - name: Add Docker GPG key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      become: yes
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present


    - name: Update apt package cache
      become: yes
      apt:
        update_cache: yes



    - name: Install Docker packages
      become: yes
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present



    - name: Start Docker service
      become: yes
      service:
        name: docker
        state: started
        enabled: yes



    - name: Pull an image
      docker_image:
        name: httpd
        source: pull


    - name: Build image with build args
      docker_image:
        name: httpd
        build:
          path: "{{dockerfile_path}}" 
        source: build
        state: present
      notify: Archive container 


    - name: archive container image as a tarball
      docker_image:
        name: httpd
        archive_path: /home/vagrant/tarfile/httpd_conatiner.tar
        source: pull
        state: present


    - name: Run Docker container
      docker_container:
        name: my_container
        image: httpd
        state: started
        ports:
          - "80:80"
